"""
core/rspamd.py – Generate Rspamd local config files and manage the service.
"""

import os
import subprocess
from typing import Tuple

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from core.fileio import read_json

RSPAMD_CFG  = os.path.join(BASE_DIR, "config", "rspamd.json")

# Target paths on the Linux production server
RSPAMD_LOCAL_D    = "/etc/rspamd/local.d"
WORKER_CONF       = os.path.join(RSPAMD_LOCAL_D, "worker-normal.inc")
RATELIMIT_CONF    = os.path.join(RSPAMD_LOCAL_D, "ratelimit.conf")
ACTIONS_CONF      = os.path.join(RSPAMD_LOCAL_D, "actions.conf")


def get_config() -> dict:
    return read_json(RSPAMD_CFG, {
        "enable":         True,
        "required_score": 6.0,
        "greylist":       True,
        "rate_limit": {
            "enable": True,
            "burst":  100,
            "rate":   "50 / 1min"
        },
        "whitelist_ips":     [],
        "blacklist_domains": []
    })


def get_status() -> str:
    """Return 'running' | 'stopped' | 'unknown'."""
    return _service_status("rspamd")


def generate_config() -> Tuple[bool, str]:
    """
    Write Rspamd local.d config files based on config/rspamd.json.
    Returns (success, message).
    """
    cfg = get_config()

    os.makedirs(RSPAMD_LOCAL_D, exist_ok=True)

    # --- actions.conf (scoring) ---
    score      = cfg.get("required_score", 6.0)
    greylist   = cfg.get("greylist", True)
    greylist_line = f'  greylist = {score - 1.5:.1f};' if greylist else ""

    actions_content = f"""# Generated by Postfix Relay Panel
actions {{
  reject = {score + 9.0:.1f};
  add_header = {score:.1f};
{greylist_line}
}}
"""
    # --- ratelimit.conf ---
    rl     = cfg.get("rate_limit", {})
    rl_en  = rl.get("enable", True)
    burst  = rl.get("burst", 100)
    rate   = rl.get("rate", "50 / 1min")

    if rl_en:
        ratelimit_content = f"""# Generated by Postfix Relay Panel
ratelimit {{
  rates {{
    to = {{
      burst = {burst};
      rate  = "{rate}";
    }};
  }};
}}
"""
    else:
        ratelimit_content = "# Rate limiting disabled\nratelimit { enabled = false; }\n"

    # --- whitelist / blacklist ---
    wl_ips     = cfg.get("whitelist_ips", [])
    bl_domains = cfg.get("blacklist_domains", [])

    whitelist_content = ""
    if wl_ips:
        entries = "\n".join(f'  "{ip}" : 1;' for ip in wl_ips)
        whitelist_content = f"ip_whitelist {{\n{entries}\n}}\n"

    try:
        _write_if_possible(ACTIONS_CONF,   actions_content)
        _write_if_possible(RATELIMIT_CONF, ratelimit_content)
        if wl_ips:
            wl_path = os.path.join(RSPAMD_LOCAL_D, "whitelist.conf")
            _write_if_possible(wl_path, whitelist_content)
        return True, "Config files generated successfully."
    except PermissionError as e:
        return False, f"Permission denied writing Rspamd config: {e} (run as root on server)"
    except Exception as e:
        return False, str(e)


def reload_rspamd() -> Tuple[bool, str]:
    """Run configtest then reload. Returns (success, output)."""
    ok, msg = _run("rspamadm configtest")
    if not ok:
        return False, f"Config test failed: {msg}"
    ok2, msg2 = _run("systemctl reload rspamd")
    if not ok2:
        return False, f"Reload failed: {msg2}"
    return True, "Rspamd reloaded successfully."


# ── Internal helpers ─────────────────────────────────────────────────────────

def _run(cmd: str) -> Tuple[bool, str]:
    """Run a shell command and return (success, output)."""
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=15
        )
        out = (result.stdout + result.stderr).strip()
        return result.returncode == 0, out
    except FileNotFoundError:
        return False, f"Command not found: {cmd} (expected Linux environment)"
    except Exception as e:
        return False, str(e)


def _service_status(service: str) -> str:
    ok, out = _run(f"systemctl is-active {service}")
    if ok and out.strip() == "active":
        return "running"
    return "stopped"


def _write_if_possible(path: str, content: str) -> None:
    """Only write if on Linux (path starts with /etc)."""
    if not path.startswith("/"):
        return  # skip on Windows dev
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
