"""
core/rspamd.py – Generate Rspamd local config files and manage the service.
Supports Rate limit, Virus scan, URL BL, DKIM policy, Fuzzy hash, and Custom Lua.
"""
import os
from typing import Tuple, Dict, Any

from core.fileio import read_json
from core.system_safe import safe_write_config, safe_reload_rspamd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RSPAMD_CFG = os.path.join(BASE_DIR, "config", "rspamd.json")

# Target paths on the Linux production server
RSPAMD_LOCAL_D = "/etc/rspamd/local.d"

def get_config() -> Dict[str, Any]:
    return read_json(RSPAMD_CFG, {
        "enable": True,
        "required_score": 6.0,
        "greylist": True,
        "rate_limit": {"enable": True, "burst": 100, "rate": "50 / 1min"},
        "virus_scan": {"enable": False, "type": "clamav", "socket": "/var/run/clamav/clamd.ctl"},
        "url_blacklist": {"enable": True, "custom_domains": []},
        "dkim_policy": {"enable": True, "verification": True, "signing": False},
        "fuzzy_hash": {"enable": False, "threshold": 10.0},
        "custom_lua": "",
        "whitelist_ips": [],
        "blacklist_domains": []
    })

def get_status() -> str:
    """Check if service is active."""
    import subprocess
    try:
        res = subprocess.run("systemctl is-active rspamd", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        return "running" if res.stdout.strip() == "active" else "stopped"
    except:
        return "unknown"

def generate_config() -> Tuple[bool, str]:
    """
    Generates all Rspamd local.d configs and reloads safely.
    """
    cfg = get_config()
    if not cfg.get("enable", True):
        return True, "Rspamd config generation skipped (Disabled in settings)."

    results = []
    
    # 1. actions.conf
    score = cfg.get("required_score", 6.0)
    greylist = cfg.get("greylist", True)
    greylist_line = f'  greylist = {score - 1.5:.1f};' if greylist else ""
    actions_content = f"""# Generated by Postfix Relay Panel
actions {{
  reject = {score + 9.0:.1f};
  add_header = {score:.1f};
{greylist_line}
}}"""
    results.append(safe_write_config(os.path.join(RSPAMD_LOCAL_D, "actions.conf"), actions_content))

    # 2. ratelimit.conf
    rl = cfg.get("rate_limit", {})
    rl_content = ""
    if rl.get("enable", True):
        rl_content = f"""ratelimit {{
  rates {{
    user = {{
      burst = {rl.get('burst', 100)};
      rate = "{rl.get('rate', '50 / 1min')}";
    }}
  }}
}}"""
    else:
        rl_content = "ratelimit { enabled = false; }"
    results.append(safe_write_config(os.path.join(RSPAMD_LOCAL_D, "ratelimit.conf"), rl_content))

    # 3. antivirus.conf (ClamAV)
    vs = cfg.get("virus_scan", {})
    vs_content = "clamav { enabled = false; }"
    if vs.get("enable", False):
        vs_content = f"""clamav {{
  symbol = "CLAM_VIRUS";
  type = "{vs.get('type', 'clamav')}";
  servers = "{vs.get('socket', '/var/run/clamav/clamd.ctl')}";
  action = "reject";
  scan_mime_parts = true;
}}"""
    results.append(safe_write_config(os.path.join(RSPAMD_LOCAL_D, "antivirus.conf"), vs_content))

    # 4. multimap.conf (URL BL & Domain BL)
    url_bl = cfg.get("url_blacklist", {})
    custom_domains = url_bl.get("custom_domains", [])
    map_dir = "/etc/rspamd/maps.d"
    os.makedirs(map_dir, exist_ok=True)
    
    domain_bl_content = "\n".join(custom_domains)
    safe_write_config(os.path.join(map_dir, "custom_bl_domains.map"), domain_bl_content)
    
    multimap_content = """# Generated by Postfix Relay Panel
CUSTOM_DOMAIN_BL {
  type = "dnsbl";
  map = "file:///etc/rspamd/maps.d/custom_bl_domains.map";
  symbol = "CUSTOM_DOMAIN_BL";
  description = "Custom Blacklisted Domain";
  score = 5.0;
}"""
    results.append(safe_write_config(os.path.join(RSPAMD_LOCAL_D, "multimap.conf"), multimap_content))

    # 5. fuzzy_check.conf
    fz = cfg.get("fuzzy_hash", {})
    fz_content = f"enabled = {'true' if fz.get('enable') else 'false'};"
    results.append(safe_write_config(os.path.join(RSPAMD_LOCAL_D, "fuzzy_check.conf"), fz_content))

    # 6. custom.lua
    lua_code = cfg.get("custom_lua", "")
    if lua_code:
        # Basic Lua safety check could be added here
        results.append(safe_write_config(os.path.join(RSPAMD_LOCAL_D, "custom.lua"), lua_code))

    # Check if any write failed
    for ok, msg in results:
        if not ok and not msg.startswith("Bypassing system command"):
            return False, f"Failed during config generation: {msg}"

    # Reload safely
    return safe_reload_rspamd()
